ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'PAYMENT_SUCCEEDED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'PAYMENT_FAILED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'REQUISITION_READY';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'LAB_SUBMISSION_FAILED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'MANUAL_REVIEW_REQUIRED';
