import { ILabCenter } from './lab-centers.types';

const now = new Date();

export const fallbackLabCenters: ILabCenter[] = [
  {
    id: 'seed-nyc-quest',
    name: 'Quest Diagnostics - Midtown Manhattan',
    address: '330 W 34th St, New York, NY 10001',
    phone: '(212) 555-0148',
    email: null,
    website: 'https://www.questdiagnostics.com',
    type: 'Quest Diagnostics',
    hours: 'Mon-Fri 7:00 AM - 5:00 PM',
    status: 'Open',
    latitude: 40.7505,
    longitude: -73.9934,
    rating: 4.5,
    reviewCount: 214,
    isActive: true,
    lastVerified: now,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'seed-la-labcorp',
    name: 'Labcorp - Downtown Los Angeles',
    address: '700 W 7th St, Los Angeles, CA 90017',
    phone: '(213) 555-0176',
    email: null,
    website: 'https://www.labcorp.com',
    type: 'Labcorp',
    hours: 'Mon-Fri 7:30 AM - 5:30 PM',
    status: 'Open',
    latitude: 34.0522,
    longitude: -118.2437,
    rating: 4.3,
    reviewCount: 189,
    isActive: true,
    lastVerified: now,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'seed-chi-quest',
    name: 'Quest Diagnostics - Chicago Loop',
    address: '50 S Wacker Dr, Chicago, IL 60606',
    phone: '(312) 555-0192',
    email: null,
    website: 'https://www.questdiagnostics.com',
    type: 'Quest Diagnostics',
    hours: 'Mon-Fri 7:00 AM - 5:00 PM',
    status: 'Open',
    latitude: 41.8781,
    longitude: -87.6298,
    rating: 4.4,
    reviewCount: 162,
    isActive: true,
    lastVerified: now,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'seed-hou-labcorp',
    name: 'Labcorp - Downtown Houston',
    address: '1200 McKinney St, Houston, TX 77010',
    phone: '(713) 555-0133',
    email: null,
    website: 'https://www.labcorp.com',
    type: 'Labcorp',
    hours: 'Mon-Fri 7:00 AM - 5:30 PM',
    status: 'Open',
    latitude: 29.7604,
    longitude: -95.3698,
    rating: 4.2,
    reviewCount: 121,
    isActive: true,
    lastVerified: now,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'seed-phx-hospital',
    name: 'Valley Hospital Lab - Phoenix',
    address: '1919 E Thomas Rd, Phoenix, AZ 85016',
    phone: '(602) 555-0110',
    email: null,
    website: 'https://www.bannerhealth.com',
    type: 'Hospital Lab',
    hours: 'Mon-Sun 6:00 AM - 8:00 PM',
    status: 'Open',
    latitude: 33.4484,
    longitude: -112.074,
    rating: 4.6,
    reviewCount: 98,
    isActive: true,
    lastVerified: now,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'seed-mia-urgent',
    name: 'South Beach Urgent Care Lab',
    address: '500 Collins Ave, Miami Beach, FL 33139',
    phone: '(305) 555-0159',
    email: null,
    website: 'https://www.urgentcare.com',
    type: 'Urgent Care',
    hours: 'Mon-Sun 8:00 AM - 8:00 PM',
    status: 'Open',
    latitude: 25.7617,
    longitude: -80.1918,
    rating: 4.1,
    reviewCount: 77,
    isActive: true,
    lastVerified: now,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'seed-sea-clinic',
    name: 'Puget Sound Medical Clinic Lab',
    address: '1201 3rd Ave, Seattle, WA 98101',
    phone: '(206) 555-0188',
    email: null,
    website: 'https://www.swedish.org',
    type: 'Medical Clinic',
    hours: 'Mon-Fri 7:00 AM - 6:00 PM',
    status: 'Open',
    latitude: 47.6062,
    longitude: -122.3321,
    rating: 4.5,
    reviewCount: 142,
    isActive: true,
    lastVerified: now,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'seed-den-quest',
    name: 'Quest Diagnostics - Downtown Denver',
    address: '707 17th St, Denver, CO 80202',
    phone: '(303) 555-0164',
    email: null,
    website: 'https://www.questdiagnostics.com',
    type: 'Quest Diagnostics',
    hours: 'Mon-Fri 7:00 AM - 5:00 PM',
    status: 'Open',
    latitude: 39.7392,
    longitude: -104.9903,
    rating: 4.3,
    reviewCount: 113,
    isActive: true,
    lastVerified: now,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'seed-bos-labcorp',
    name: 'Labcorp - Back Bay',
    address: '800 Boylston St, Boston, MA 02199',
    phone: '(617) 555-0122',
    email: null,
    website: 'https://www.labcorp.com',
    type: 'Labcorp',
    hours: 'Mon-Fri 7:30 AM - 5:30 PM',
    status: 'Open',
    latitude: 42.3601,
    longitude: -71.0589,
    rating: 4.4,
    reviewCount: 134,
    isActive: true,
    lastVerified: now,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'seed-atl-hospital',
    name: 'Atlanta General Hospital Lab',
    address: '80 Jesse Hill Jr Dr SE, Atlanta, GA 30303',
    phone: '(404) 555-0171',
    email: null,
    website: 'https://www.gradyhealth.org',
    type: 'Hospital Lab',
    hours: 'Mon-Sun 6:00 AM - 8:00 PM',
    status: 'Open',
    latitude: 33.749,
    longitude: -84.388,
    rating: 4.2,
    reviewCount: 88,
    isActive: true,
    lastVerified: now,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'seed-sf-urgent',
    name: 'Market Street Urgent Care Lab',
    address: '1355 Market St, San Francisco, CA 94103',
    phone: '(415) 555-0103',
    email: null,
    website: 'https://www.urgentcare.com',
    type: 'Urgent Care',
    hours: 'Mon-Sun 8:00 AM - 8:00 PM',
    status: 'Open',
    latitude: 37.7749,
    longitude: -122.4194,
    rating: 4.0,
    reviewCount: 95,
    isActive: true,
    lastVerified: now,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'seed-lv-clinic',
    name: 'Desert Springs Medical Clinic Lab',
    address: '201 N Buffalo Dr, Las Vegas, NV 89145',
    phone: '(702) 555-0199',
    email: null,
    website: 'https://www.ezlabtesting.com',
    type: 'Medical Clinic',
    hours: 'Mon-Fri 7:00 AM - 6:00 PM',
    status: 'Open',
    latitude: 36.1699,
    longitude: -115.1398,
    rating: 4.6,
    reviewCount: 156,
    isActive: true,
    lastVerified: now,
    createdAt: now,
    updatedAt: now,
  },
];
